name = "cloudworker-proxy-example"
main = "src/server.ts"
compatibility_date = "2022-07-06"

# Add your account_id here..
account_id = "0c8c22bdcd98c3dc6a35190650ef7906"

kv_namespaces = []

route = { pattern = "proxy.ahlstrand.es/*", zone_id = "b56a76d859fe2ed6a8d77270cd2e8ba8" }

[vars]
